name: flutter_supabase
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.7
  flutter_dotenv: ^5.1.0
  curved_navigation_bar: 1.0.6
  flutter_riverpod: ^2.0.0
  image_picker: ^0.8.4+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: 2.1.0
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  assets:
    - .env
